import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../../api/client";
import { changeBrandActivity, changeCategoryActivity, createBrand, createCategory, deleteBrand, deleteCategory, getBrands, getCategories, updateBrand, updateCategory } from "../services/catalogApi";
import type { Brand, BrandFormData, CategoryFormData, ProductCategory } from "../types/catalog";

const emptyBrand: BrandFormData = { title: "", logo: "", sort_order: 0, is_active: true, description: "" };
const emptyCategory: CategoryFormData = { title: "", parent_id: "", sort_order: 0, is_active: true, description: "" };

export function CatalogPage() {
  const [brands, setBrands] = useState<Brand[]>([]); const [categories, setCategories] = useState<ProductCategory[]>([]);
  const [brandSearch, setBrandSearch] = useState(""); const [categorySearch, setCategorySearch] = useState("");
  const [brandForm, setBrandForm] = useState<BrandFormData>(emptyBrand); const [categoryForm, setCategoryForm] = useState<CategoryFormData>(emptyCategory);
  const [editingBrand, setEditingBrand] = useState<string | null>(null); const [editingCategory, setEditingCategory] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => { setLoading(true); setError(null); try { const [b, c] = await Promise.all([getBrands({ per_page: 100 }), getCategories({ per_page: 100 })]); setBrands(b.data); setCategories(c.data); } catch (e: unknown) { setError(e instanceof ApiError ? e.message : "خطا در دریافت برندها و دسته‌بندی‌ها."); } finally { setLoading(false); } }, []);
  useEffect(() => { const t = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(t); }, [load]);

  const filteredBrands = brands.filter((b) => `${b.title} ${b.code}`.toLocaleLowerCase().includes(brandSearch.trim().toLocaleLowerCase()));
  const filteredCategories = categories.filter((c) => `${c.title} ${c.code}`.toLocaleLowerCase().includes(categorySearch.trim().toLocaleLowerCase()));
  const parentOptions = categories.filter((c) => c.id !== editingCategory);

  async function saveBrand(e: React.FormEvent) { e.preventDefault(); if (!brandForm.title.trim() || saving) return; setSaving(true); setError(null); try { if (editingBrand) await updateBrand(editingBrand, brandForm); else await createBrand(brandForm); setBrandForm(emptyBrand); setEditingBrand(null); await load(); } catch (x: unknown) { setError(x instanceof ApiError ? x.message : "خطا در ذخیره برند."); } finally { setSaving(false); } }
  async function saveCategory(e: React.FormEvent) { e.preventDefault(); if (!categoryForm.title.trim() || saving) return; setSaving(true); setError(null); try { if (editingCategory) await updateCategory(editingCategory, categoryForm); else await createCategory(categoryForm); setCategoryForm(emptyCategory); setEditingCategory(null); await load(); } catch (x: unknown) { setError(x instanceof ApiError ? x.message : "خطا در ذخیره دسته‌بندی."); } finally { setSaving(false); } }
  async function removeBrand(b: Brand) { if (!window.confirm(`آیا از حذف «${b.title}» مطمئن هستید؟`)) return; try { await deleteBrand(b.id); await load(); } catch (x: unknown) { setError(x instanceof ApiError ? x.message : "خطا در حذف برند."); } }
  async function removeCategory(c: ProductCategory) { if (!window.confirm(`آیا از حذف «${c.title}» مطمئن هستید؟`)) return; try { await deleteCategory(c.id); await load(); } catch (x: unknown) { setError(x instanceof ApiError ? x.message : "خطا در حذف دسته‌بندی."); } }

  return <section className="space-y-6 p-4 md:p-6"><header className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold">برندها و دسته‌بندی‌ها</h1><p className="text-sm text-gray-500">مدیریت ساختار کاتالوگ محصولات</p></div><button type="button" disabled={loading} onClick={() => void load()} className="rounded-lg border px-4 py-2 text-sm disabled:opacity-50">بروزرسانی</button></header>
    {error && <div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 xl:grid-cols-2">
      <div className="space-y-4 rounded-xl border bg-white p-4"><div><h2 className="font-semibold">برندها</h2><p className="text-xs text-gray-500">کد برند به‌صورت خودکار تولید می‌شود.</p></div>
        <form onSubmit={saveBrand} className="grid gap-3 md:grid-cols-2"><input required disabled={saving} value={brandForm.title} onChange={(e) => setBrandForm({ ...brandForm, title: e.target.value })} placeholder="نام برند" className="rounded-lg border px-3 py-2" /><input disabled={saving} value={brandForm.logo} onChange={(e) => setBrandForm({ ...brandForm, logo: e.target.value })} placeholder="آدرس لوگو (اختیاری)" className="rounded-lg border px-3 py-2" /><input min={0} type="number" disabled={saving} value={brandForm.sort_order} onChange={(e) => setBrandForm({ ...brandForm, sort_order: Math.max(0, Number(e.target.value)) })} placeholder="ترتیب" className="rounded-lg border px-3 py-2" /><label className="flex items-center gap-2 rounded-lg border px-3 py-2"><input type="checkbox" disabled={saving} checked={brandForm.is_active} onChange={(e) => setBrandForm({ ...brandForm, is_active: e.target.checked })} />فعال</label><textarea disabled={saving} value={brandForm.description} onChange={(e) => setBrandForm({ ...brandForm, description: e.target.value })} placeholder="توضیحات" className="min-h-20 rounded-lg border px-3 py-2 md:col-span-2" /><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="rounded-lg bg-gray-900 px-4 py-2 text-sm text-white">{editingBrand ? "ذخیره تغییرات" : "افزودن برند"}</button>{editingBrand && <button type="button" disabled={saving} onClick={() => { setEditingBrand(null); setBrandForm(emptyBrand); }} className="rounded-lg border px-4 py-2 text-sm">انصراف</button>}</div></form>
        <input value={brandSearch} onChange={(e) => setBrandSearch(e.target.value)} placeholder="جستجوی برند" className="w-full rounded-lg border px-3 py-2 text-sm" />
        <div className="divide-y rounded-lg border">{loading ? <p className="p-6 text-center text-sm">در حال دریافت…</p> : filteredBrands.length === 0 ? <p className="p-6 text-center text-sm text-gray-500">برندی پیدا نشد.</p> : filteredBrands.map((b) => <div key={b.id} className="flex items-center justify-between gap-3 p-3"><div><div className="font-medium">{b.title}</div><div className="text-xs text-gray-500">{b.code} · {b.is_active ? "فعال" : "غیرفعال"}</div></div><div className="flex gap-2"><button type="button" onClick={() => { setEditingBrand(b.id); setBrandForm({ title: b.title, logo: b.logo ?? "", sort_order: b.sort_order, is_active: b.is_active, description: b.description ?? "" }); }} className="rounded border px-2 py-1 text-xs">ویرایش</button><button type="button" onClick={() => void changeBrandActivity(b.id, !b.is_active).then(load).catch((x: unknown) => setError(x instanceof ApiError ? x.message : "خطا در تغییر وضعیت برند."))} className="rounded border px-2 py-1 text-xs">{b.is_active ? "غیرفعال" : "فعال"}</button><button type="button" onClick={() => void removeBrand(b)} className="rounded border px-2 py-1 text-xs text-red-600">حذف</button></div></div>)}</div>
      </div>
      <div className="space-y-4 rounded-xl border bg-white p-4"><div><h2 className="font-semibold">دسته‌بندی محصولات</h2><p className="text-xs text-gray-500">دسته‌ها می‌توانند والد داشته باشند.</p></div>
        <form onSubmit={saveCategory} className="grid gap-3 md:grid-cols-2"><input required disabled={saving} value={categoryForm.title} onChange={(e) => setCategoryForm({ ...categoryForm, title: e.target.value })} placeholder="نام دسته‌بندی" className="rounded-lg border px-3 py-2" /><select disabled={saving} value={categoryForm.parent_id} onChange={(e) => setCategoryForm({ ...categoryForm, parent_id: e.target.value })} className="rounded-lg border px-3 py-2"><option value="">بدون والد</option>{parentOptions.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}</select><input min={0} type="number" disabled={saving} value={categoryForm.sort_order} onChange={(e) => setCategoryForm({ ...categoryForm, sort_order: Math.max(0, Number(e.target.value)) })} placeholder="ترتیب" className="rounded-lg border px-3 py-2" /><label className="flex items-center gap-2 rounded-lg border px-3 py-2"><input type="checkbox" disabled={saving} checked={categoryForm.is_active} onChange={(e) => setCategoryForm({ ...categoryForm, is_active: e.target.checked })} />فعال</label><textarea disabled={saving} value={categoryForm.description} onChange={(e) => setCategoryForm({ ...categoryForm, description: e.target.value })} placeholder="توضیحات" className="min-h-20 rounded-lg border px-3 py-2 md:col-span-2" /><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="rounded-lg bg-gray-900 px-4 py-2 text-sm text-white">{editingCategory ? "ذخیره تغییرات" : "افزودن دسته‌بندی"}</button>{editingCategory && <button type="button" disabled={saving} onClick={() => { setEditingCategory(null); setCategoryForm(emptyCategory); }} className="rounded-lg border px-4 py-2 text-sm">انصراف</button>}</div></form>
        <input value={categorySearch} onChange={(e) => setCategorySearch(e.target.value)} placeholder="جستجوی دسته‌بندی" className="w-full rounded-lg border px-3 py-2 text-sm" />
        <div className="divide-y rounded-lg border">{loading ? <p className="p-6 text-center text-sm">در حال دریافت…</p> : filteredCategories.length === 0 ? <p className="p-6 text-center text-sm text-gray-500">دسته‌بندی‌ای پیدا نشد.</p> : filteredCategories.map((c) => { const parent = categories.find((p) => p.id === c.parent_id); return <div key={c.id} className="flex items-center justify-between gap-3 p-3"><div><div className="font-medium">{c.title}</div><div className="text-xs text-gray-500">{c.code}{parent ? ` · والد: ${parent.title}` : " · ریشه"} · {c.is_active ? "فعال" : "غیرفعال"}</div></div><div className="flex gap-2"><button type="button" onClick={() => { setEditingCategory(c.id); setCategoryForm({ title: c.title, parent_id: c.parent_id ?? "", sort_order: c.sort_order, is_active: c.is_active, description: c.description ?? "" }); }} className="rounded border px-2 py-1 text-xs">ویرایش</button><button type="button" onClick={() => void changeCategoryActivity(c.id, !c.is_active).then(load).catch((x: unknown) => setError(x instanceof ApiError ? x.message : "خطا در تغییر وضعیت دسته‌بندی."))} className="rounded border px-2 py-1 text-xs">{c.is_active ? "غیرفعال" : "فعال"}</button><button type="button" onClick={() => void removeCategory(c)} className="rounded border px-2 py-1 text-xs text-red-600">حذف</button></div></div>; })}</div>
      </div>
    </div>
  </section>;
}
